services:
  regen:
    build: ./build
    container_name: reGen
    tty: true
    group_add:
      - video
    volumes:
      - ./models/:/horde-worker-reGen/models/
      - ./bridgeData.yaml:/horde-worker-reGen/bridgeData.yaml:ro
    devices:
      - /dev/kfd
      - /dev/dri
