services:
  reGen:
    build: ./build
    container_name: reGen
    tty: true
    group_add:
      - video
    volumes:
      - ./reGen/:/home/rocm-user/horde-worker-reGen/:rw
    devices:
      - /dev/kfd
      - /dev/dri
